import ExcelJS from 'exceljs';
import { addDays, endOfMonth, format, startOfMonth } from 'date-fns';
import { baseNameOf, metTarget, type Department, type Kpi, type Pillar } from '../types';
import { cellDate, cellNumber, cellText, norm } from './excelUpload';
import type { UploadDailyRow, UploadLeadingRow, UploadTargetRow } from './data';

// ============================================================================
// The per-department Excel template.
//
// Unlike the OPS workbooks (a fixed file the Operations team already had,
// parsed by excelUpload.ts), this workbook is GENERATED by the app from the
// department's own KPI list — so a department admin never has to match a
// layout someone else designed, and the upload can match columns to KPIs by
// exact name with no translation table. Adding a KPI in Admin → KPIs and
// downloading a fresh template is all it takes to start uploading it.
//
//   Daily       Date | Shift* | one column per Board KPI   (* only when any
//   Targets     Date | Shift* | one column per Board KPI      KPI is split
//   Next 24hrs  Date | one column per Next 24 Hours KPI       Day/Night)
//   How to use  instructions
//
// Values are typed exactly as the board shows them — 95 for 95%. (A cell
// formatted as a percentage in Excel stores 0.95; that's detected from the
// cell's number format and converted, so both work.)
// ============================================================================

export const SHEET_DAILY = 'Daily';
export const SHEET_TARGETS = 'Targets';
export const SHEET_NEXT24 = 'Next 24hrs';

interface TemplateKpi {
  base: string;
  pillar: Pillar;
  unit: string;
  split: boolean;
  isHigherBetter: boolean;
  target: number;
  sortOrder: number;
}

/** Board KPIs (lagging, visible, not old-calculation) grouped Day/Night
 * into one column each, in board order: pillar, then sort order. */
function templateColumns(kpis: Kpi[], pillars: Pillar[], leading: boolean): TemplateKpi[] {
  const pillarById = new Map(pillars.map((p) => [p.id, p]));
  const map = new Map<string, TemplateKpi>();
  for (const k of kpis) {
    if (k.is_leading !== leading || !k.active || k.is_secondary) continue;
    const pillar = pillarById.get(k.pillar_id);
    if (!pillar) continue;
    const base = baseNameOf(k.name);
    const g = map.get(base) ?? { base, pillar, unit: k.unit, split: false, isHigherBetter: k.is_higher_better, target: Number(k.target), sortOrder: k.sort_order };
    if (/\((Day|Night)\)\s*$/i.test(k.name)) g.split = true;
    g.sortOrder = Math.min(g.sortOrder, k.sort_order);
    map.set(base, g);
  }
  return Array.from(map.values()).sort((a, b) => a.pillar.sort_order - b.pillar.sort_order || a.sortOrder - b.sortOrder || a.base.localeCompare(b.base));
}

const HEADER_FILL: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1F403C' } };
const KEY_FILL: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEDF1F0' } };

function styleHeader(row: ExcelJS.Row) {
  row.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  row.alignment = { vertical: 'middle', wrapText: true };
  row.height = 34;
  row.eachCell((c) => {
    c.fill = HEADER_FILL;
  });
}

function addDateShiftSheet(wb: ExcelJS.Workbook, name: string, cols: TemplateKpi[], withShift: boolean, monthStart: Date, noteFor: (k: TemplateKpi) => string) {
  const ws = wb.addWorksheet(name, { views: [{ state: 'frozen', xSplit: withShift ? 2 : 1, ySplit: 1 }] });
  const header = ['Date', ...(withShift ? ['Shift'] : []), ...cols.map((c) => c.base)];
  ws.addRow(header);
  styleHeader(ws.getRow(1));
  ws.getColumn(1).width = 13;
  if (withShift) ws.getColumn(2).width = 9;
  const first = withShift ? 3 : 2;
  cols.forEach((c, i) => {
    const col = ws.getColumn(first + i);
    col.width = Math.max(14, Math.min(28, c.base.length + 4));
    col.numFmt = '0.##';
    ws.getRow(1).getCell(first + i).note = noteFor(c);
  });
  // Pre-filled date rows for the current month, so people only type values.
  for (let d = monthStart; d <= endOfMonth(monthStart); d = addDays(d, 1)) {
    const utc = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
    for (const shift of withShift ? ['Day', 'Night'] : [null]) {
      const row = ws.addRow([utc, ...(shift ? [shift] : [])]);
      row.getCell(1).numFmt = 'yyyy-mm-dd';
      row.getCell(1).fill = KEY_FILL;
      if (shift) row.getCell(2).fill = KEY_FILL;
    }
  }
  ws.getColumn(1).numFmt = 'yyyy-mm-dd';
  if (withShift) {
    // Day/Night dropdown on the pre-filled rows plus room to add more.
    const last = ws.rowCount + 100; // fixed up front — touching a cell adds rows
    for (let r = 2; r <= last; r++) {
      ws.getCell(r, 2).dataValidation = { type: 'list', allowBlank: true, formulae: ['"Day,Night"'] };
    }
  }
  return ws;
}

/** Builds the department's upload template as an .xlsx file. */
export async function buildDepartmentTemplate(department: Department, pillars: Pillar[], kpis: Kpi[], month = new Date()): Promise<Blob> {
  const board = templateColumns(kpis, pillars, false);
  const leading = templateColumns(kpis, pillars, true);
  const withShift = board.some((c) => c.split);
  const monthStart = startOfMonth(month);

  const wb = new ExcelJS.Workbook();
  wb.creator = 'SQDC Board';
  wb.created = new Date();

  const guide = wb.addWorksheet('How to use');
  guide.getColumn(1).width = 110;
  const lines = [
    `${department.name} — SQDC upload template`,
    '',
    `1. Daily: one row per date${withShift ? ' and shift (Day / Night)' : ''}. Type each KPI's actual value for that day. Leave a cell empty if there's no figure yet — empty cells are skipped, never written as zero.`,
    `2. Targets (optional): same layout. Only fill a cell when that day's target differs from the KPI's standard target — empty cells use the standard target set in Admin → KPIs.`,
    leading.length > 0 ? `3. Next 24hrs: one row per date with the day's projection for each Next 24 Hours KPI.` : '3. (No Next 24 Hours KPIs are set up yet, so there is no Next 24hrs sheet.)',
    '',
    'Type numbers exactly as the board shows them: 95 for 95%, 12.5 for 12.5 hours. Dates as YYYY-MM-DD (or any real Excel date).',
    'You can add more date rows at the bottom, delete rows you do not need, and re-upload the same file as often as you like — re-uploading only updates the dates in the file.',
    '',
    'Do not rename or reorder the KPI column headings: the upload matches each column to its KPI by its exact name.',
    'Added or renamed a KPI in Admin → KPIs? Download a fresh template — an old one will not have its column.',
    withShift ? 'KPIs tracked as a single daily figure (no Day/Night split) take their value from whichever shift row has it filled in.' : '',
    '',
    `Generated ${format(new Date(), 'd MMM yyyy HH:mm')} for ${department.name}.`,
  ];
  lines.forEach((l, i) => {
    const c = guide.getCell(i + 1, 1);
    c.value = l;
    c.alignment = { wrapText: true, vertical: 'top' };
    if (i === 0) c.font = { bold: true, size: 14 };
  });

  const describe = (k: TemplateKpi) =>
    `${k.pillar.name} · ${k.unit || 'no unit'} · ${k.isHigherBetter ? 'higher' : 'lower'} is better · standard target ${k.target}${k.split ? ' · separate Day & Night values' : ' · one value per day'}`;
  addDateShiftSheet(wb, SHEET_DAILY, board, withShift, monthStart, describe);
  addDateShiftSheet(wb, SHEET_TARGETS, board, withShift, monthStart, (k) => `Leave empty to use the standard target (${k.target}).`);
  if (leading.length > 0) addDateShiftSheet(wb, SHEET_NEXT24, leading, false, monthStart, (k) => `${k.pillar.name} · ${k.unit || 'no unit'}`);
  wb.views = [{ x: 0, y: 0, width: 10000, height: 20000, firstSheet: 0, activeTab: 1, visibility: 'visible' }];

  const buf = await wb.xlsx.writeBuffer();
  return new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
}

// ---------------------------------------------------------------------------
// Reading an uploaded template back
// ---------------------------------------------------------------------------

export interface TemplateParseResult {
  daily: UploadDailyRow[];
  targets: UploadTargetRow[];
  leading: UploadLeadingRow[];
  /** Distinct dates with at least one daily value, for the preview. */
  dates: string[];
  /** Column headings that don't match any KPI in this department. */
  unknownColumns: string[];
  warnings: string[];
}

/** A date cell: a real Excel date, an Excel serial number, or text typed as
 * YYYY-MM-DD / DD/MM/YYYY. */
function readDate(v: ExcelJS.CellValue): string | null {
  const d = cellDate(v);
  if (d && !Number.isNaN(d.getTime())) return d.toISOString().slice(0, 10);
  const t = cellText(v).trim();
  let m = /^(\d{4})-(\d{1,2})-(\d{1,2})/.exec(t);
  if (m) return `${m[1]}-${m[2].padStart(2, '0')}-${m[3].padStart(2, '0')}`;
  m = /^(\d{1,2})[/.-](\d{1,2})[/.-](\d{4})$/.exec(t);
  if (m) return `${m[3]}-${m[2].padStart(2, '0')}-${m[1].padStart(2, '0')}`;
  return null;
}

/** A value cell as the board would show it. Excel stores a cell formatted
 * as a percentage as its fraction (95% -> 0.95); for a % KPI that's scaled
 * back up so it lines up with values typed plainly as 95. */
function readValue(cell: ExcelJS.Cell, unit: string): number | null {
  const n = cellNumber(cell.value);
  if (n === null) return null;
  if (unit === '%' && typeof cell.numFmt === 'string' && cell.numFmt.includes('%')) return n * 100;
  return n;
}

interface SheetLayout {
  ws: ExcelJS.Worksheet;
  dateCol: number;
  shiftCol: number | null;
  columns: { col: number; header: string }[];
}

function readLayout(ws: ExcelJS.Worksheet): SheetLayout | null {
  const header = ws.getRow(1);
  let dateCol = -1;
  let shiftCol: number | null = null;
  const columns: { col: number; header: string }[] = [];
  for (let c = 1; c <= ws.columnCount; c++) {
    const h = norm(header.getCell(c).value);
    if (!h) continue;
    if (h.toLowerCase() === 'date' && dateCol === -1) dateCol = c;
    else if (h.toLowerCase() === 'shift' && shiftCol === null) shiftCol = c;
    else columns.push({ col: c, header: h });
  }
  if (dateCol === -1) return null;
  return { ws, dateCol, shiftCol, columns };
}

function findSheet(wb: ExcelJS.Workbook, name: string): ExcelJS.Worksheet | undefined {
  return wb.worksheets.find((w) => w.name.trim().toLowerCase() === name.toLowerCase());
}

/** Resolves a template column + shift to the KPI row it writes: a split KPI
 * takes the row's shift; an unsplit one takes whichever row has a value
 * (first one wins for a date, so it doesn't matter which shift row it was
 * typed on). */
function kpiFor(kpis: Kpi[], base: string, shift: 'Day' | 'Night' | null): Kpi | undefined {
  const exact = kpis.find((k) => k.name === base);
  if (exact) return exact;
  if (shift) return kpis.find((k) => k.name === `${base} (${shift})`);
  return undefined;
}

export async function parseDepartmentTemplate(buffer: ArrayBuffer, kpis: Kpi[], uploadedBy: string | null): Promise<TemplateParseResult> {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load(buffer);
  const warnings: string[] = [];
  const unknown = new Set<string>();

  const primary = kpis.filter((k) => !k.is_secondary);
  const lagging = primary.filter((k) => !k.is_leading);
  const leadingKpis = primary.filter((k) => k.is_leading);
  const laggingBases = new Set(lagging.map((k) => baseNameOf(k.name)));
  const leadingNames = new Map(leadingKpis.map((k) => [k.name, k]));

  // ---- Targets first: daily rows snapshot that day's target. -------------
  const targets: UploadTargetRow[] = [];
  const targetMap = new Map<string, number>();
  const targetWs = findSheet(wb, SHEET_TARGETS);
  const targetLayout = targetWs ? readLayout(targetWs) : null;
  if (targetLayout) {
    targetLayout.ws.eachRow((row, r) => {
      if (r === 1) return;
      const date = readDate(row.getCell(targetLayout.dateCol).value);
      if (!date) return;
      const shiftText = targetLayout.shiftCol ? norm(row.getCell(targetLayout.shiftCol).value) : '';
      const shift = /^day/i.test(shiftText) ? 'Day' : /^night/i.test(shiftText) ? 'Night' : null;
      for (const { col, header } of targetLayout.columns) {
        if (!laggingBases.has(header)) continue;
        const kpi = kpiFor(lagging, header, shift);
        if (!kpi) continue;
        const v = readValue(row.getCell(col), kpi.unit);
        if (v === null) continue;
        const key = `${kpi.id}|${date}`;
        if (targetMap.has(key)) continue;
        targetMap.set(key, v);
        targets.push({ kpi_id: kpi.id, entry_date: date, target: v });
      }
    });
  }

  // ---- Daily values -------------------------------------------------------
  const daily: UploadDailyRow[] = [];
  const seen = new Set<string>();
  const dates = new Set<string>();
  const dailyWs = findSheet(wb, SHEET_DAILY) ?? wb.worksheets.find((w) => readLayout(w)?.columns.some((c) => laggingBases.has(c.header)));
  const layout = dailyWs ? readLayout(dailyWs) : null;
  if (!layout) {
    warnings.push(`No "${SHEET_DAILY}" sheet with a "Date" column was found — no daily values were read.`);
  } else {
    let badDates = 0;
    let missingShift = 0;
    for (const { header } of layout.columns) if (!laggingBases.has(header)) unknown.add(header);
    layout.ws.eachRow((row, r) => {
      if (r === 1) return;
      const rawDate = row.getCell(layout.dateCol).value;
      const date = readDate(rawDate);
      const hasAnyValue = layout.columns.some(({ col }) => cellNumber(row.getCell(col).value) !== null);
      if (!date) {
        if (hasAnyValue) badDates++;
        return;
      }
      const shiftText = layout.shiftCol ? norm(row.getCell(layout.shiftCol).value) : '';
      const shift = /^day/i.test(shiftText) ? 'Day' : /^night/i.test(shiftText) ? 'Night' : null;
      for (const { col, header } of layout.columns) {
        if (!laggingBases.has(header)) continue;
        const kpi = kpiFor(lagging, header, shift);
        const cell = row.getCell(col);
        if (!kpi) {
          if (cellNumber(cell.value) !== null) missingShift++;
          continue;
        }
        const actual = readValue(cell, kpi.unit);
        if (actual === null) continue;
        const key = `${kpi.id}|${date}`;
        if (seen.has(key)) continue;
        seen.add(key);
        dates.add(date);
        const target = targetMap.get(key) ?? Number(kpi.target);
        daily.push({ kpi_id: kpi.id, entry_date: date, target, actual, met_target: metTarget(kpi, target, actual), entered_by: uploadedBy });
      }
    });
    if (badDates > 0) warnings.push(`${badDates} row(s) had values but no readable date — skipped. Use YYYY-MM-DD or a real Excel date.`);
    if (missingShift > 0) warnings.push(`${missingShift} value(s) for Day/Night KPIs were on rows with no Shift — skipped. Fill in the Shift column (Day or Night).`);
  }

  // ---- Next 24hrs ---------------------------------------------------------
  const leading: UploadLeadingRow[] = [];
  const nextWs = findSheet(wb, SHEET_NEXT24);
  const nextLayout = nextWs ? readLayout(nextWs) : null;
  if (nextLayout) {
    const seenLeading = new Set<string>();
    for (const { header } of nextLayout.columns) if (!leadingNames.has(header)) unknown.add(header);
    nextLayout.ws.eachRow((row, r) => {
      if (r === 1) return;
      const date = readDate(row.getCell(nextLayout.dateCol).value);
      if (!date) return;
      for (const { col, header } of nextLayout.columns) {
        const kpi = leadingNames.get(header);
        if (!kpi) continue;
        const v = readValue(row.getCell(col), kpi.unit);
        if (v === null) continue;
        const key = `${kpi.id}|${date}`;
        if (seenLeading.has(key)) continue;
        seenLeading.add(key);
        leading.push({ kpi_id: kpi.id, entry_date: date, value: v, uploaded_by: uploadedBy });
      }
    });
  }

  return {
    daily,
    targets,
    leading,
    dates: Array.from(dates).sort(),
    unknownColumns: Array.from(unknown),
    warnings,
  };
}
