import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { departmentPath, useDepartment, useDepartments } from '../../context/DepartmentContext';
import { useEmployee } from '../../context/EmployeeContext';
import { updateDepartment } from '../../lib/data';
import { ENTRY_MODE_LABELS, errorMessage, type EntryMode, type UploadFormat } from '../../types';
import { Button, InfoTip, Select, TextField } from '../../components/ui';
import { slugify } from '../../lib/slug';

export const ENTRY_MODE_OPTIONS: { value: EntryMode; label: string }[] = [
  { value: 'manual', label: `${ENTRY_MODE_LABELS.manual} — simplest to start` },
  { value: 'upload', label: `${ENTRY_MODE_LABELS.upload} — from a spreadsheet` },
  { value: 'both', label: ENTRY_MODE_LABELS.both },
];

const UPLOAD_FORMAT_OPTIONS: { value: UploadFormat; label: string }[] = [
  { value: 'template', label: 'Template generated by this app' },
  { value: 'ops', label: 'OPS SQDC Daily / Weekly workbooks (Operations)' },
];

export default function SettingsSection() {
  const department = useDepartment();
  const { reload, applyDepartment } = useDepartments();
  const { isSiteAdmin } = useEmployee();
  const navigate = useNavigate();
  const [name, setName] = useState(department.name);
  const [slug, setSlug] = useState(department.slug);
  const [entryMode, setEntryMode] = useState<EntryMode>(department.entry_mode);
  const [uploadFormat, setUploadFormat] = useState<UploadFormat>(department.upload_format);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const dirty = name !== department.name || slug !== department.slug || entryMode !== department.entry_mode || uploadFormat !== department.upload_format;

  async function handleSave() {
    if (!name.trim()) return setError('Department name is required.');
    const cleanSlug = slugify(slug);
    if (!cleanSlug) return setError('Web address needs at least one letter or number.');
    setSaving(true);
    setError(null);
    setMessage(null);
    try {
      const updated = await updateDepartment(department.id, {
        name: name.trim(),
        slug: cleanSlug,
        entry_mode: entryMode,
        upload_format: uploadFormat,
      });
      // Same department (same id), so the page isn't remounted: the tab and
      // this message survive a change of web address.
      applyDepartment(updated);
      setMessage('Saved.');
      if (updated.slug !== department.slug) navigate(departmentPath(updated, 'admin'), { replace: true });
      void reload();
    } catch (e) {
      setError(errorMessage(e, 'Failed to save'));
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="card" style={{ marginTop: 24 }}>
      <div className="page-header-row" style={{ marginBottom: 14 }}>
        <h3>Department settings</h3>
        <Button type="button" themeColor="primary" disabled={saving || !dirty} onClick={handleSave}>
          {saving ? 'Saving…' : 'Save'}
        </Button>
      </div>
      {message && <div className="alert alert-success">{message}</div>}
      {error && <div className="alert alert-error">{error}</div>}
      <div className="form-grid">
        <label>
          Department name
          <TextField value={name} onChange={setName} />
        </label>
        <label>
          <span className="field-title">
            Board web address{' '}
          <InfoTip>
            The board's link: {window.location.origin}/d/{slug || '…'}. Changing it breaks bookmarks and TV screens using the old link, so
            only site admins can.
          </InfoTip>
          </span>
          <TextField value={slug} onChange={(v) => setSlug(v.toLowerCase())} disabled={!isSiteAdmin} />
        </label>
        <label>
          <span className="field-title">
            How data gets in{' '}
          <InfoTip>
            Typed in the app: members enter each KPI's value on the Enter Data page. Excel upload: an admin uploads a spreadsheet (Admin →
            Uploads) and members add remarks. Both: either way — a value typed in the app is never overwritten by an upload.
          </InfoTip>
          </span>
          <Select value={entryMode} onChange={(v) => setEntryMode(v as EntryMode)} options={ENTRY_MODE_OPTIONS} />
        </label>
        {entryMode !== 'manual' && (
          <label>
            <span className="field-title">
              Upload file{' '}
            <InfoTip>
              Template: download it from Admin → Uploads — it has a column for each of your KPIs. The OPS workbooks are the original
              Operations files (their own fixed layout, plus a separate Weekly workbook).
            </InfoTip>
            </span>
            <Select value={uploadFormat} onChange={(v) => setUploadFormat(v as UploadFormat)} options={UPLOAD_FORMAT_OPTIONS} />
          </label>
        )}
      </div>
      {uploadFormat !== department.upload_format && (
        <div className="alert alert-warning" style={{ marginTop: 14, marginBottom: 0 }}>
          {uploadFormat === 'ops'
            ? 'With the OPS workbook format, the Weekly view shows figures from the OPS Weekly upload instead of rolling up the daily values.'
            : 'With the template format, the Weekly view rolls up each KPI from its daily values instead of reading an uploaded Weekly workbook.'}
        </div>
      )}
    </div>
  );
}
